mainIine/foe-helfer-extension

js/web/unit.js

Fehler wurden begangen D: habs mal korrigiert, damit funktioniert die Armeeübersicht ;)

Fehler bei If-Abfragen

---

js/web/productions.js

Mehrfache Einträge in Produktionsübersicht verhindern

---

js/web/settings.js

Umbenennung wurde hier vergessen 😄

Fehler behoben -> Geht nun wieder

---

js/web/ant.js

Ich habe mal das Abfangen der AJAX/XHR umgebaut.
Mit diesem EventHandler Modell können die einzelnen Auswertungen in die entsprechenden Dateien ausgelagert werden und es sammelt sich nicht alles in der ant.js Datei.
Auch kann man neue "Module" über die Entwickler Konsole testen und anpassen, ohne die Seite jedes mal neu zu laden.
Was haltet ihr davon?
Die bisherige Funktionalität bleibt (soweit ich das getestet habe) unverändert und dies könnte (meiner Meinung nach) zu schönerem Code führen.

Das abfangen der AJAX/XHR Anfragen wird nun über Event-Handler geregelt.

---

js/web/guildfights/css/guildfights.css
js/web/guildfights/js/guildfights.js

- Korrekte Auswertung neuer Ergnisse

---

js/web/_i18n/de.js
js/web/eventquest/js/eventquest.js
js/web/eventquest/questlist/questlist.json
js/web/guildfights/js/guildfights.js
js/web/infoboard/js/infoboard.js
js/web/strategy-points/js/strategy-points.js

- Infobox um Gildengefechte erweitert

---

_locales/ro/messages.json
js/web/i18n/ro.js

Added romanian translation 

---

js/web/_i18n/fr.js

Updated and corrected french beta translations

French Translation Updates and Fixes

---

css/web/style-menu.css
js/web/_menu/js/_menu.js
js/web/citymap/css/citymap.css

- Menü lässt sich via Drag&Drop sortieren
- Menü gibt keine doppelten Item mehr aus
- für Merlin eine transition hinzugefügt :-)

Menü umgebaut

---

js/web/_i18n/cs.json
js/web/_i18n/de.json
js/web/_i18n/en.json
js/web/_i18n/es.json
js/web/_i18n/fr.json
js/web/_i18n/ro.json
js/web/_i18n/ru.json
js/web/_i18n/sv.json
js/web/_main/js/_main.js
js/web/calculator/js/calculator.js
js/web/investment/js/investment.js

- Arche Bonus wird global ermittelt und zur Verfügung gestellt
- Typo gefixt, Arc => Ark _(Es geht nicht um das Schiff, sondern um das Gebäude. Inno übersetzt falsch ;-) )_

Arche Bonus + Typo

---

js/web/_i18n/fr.json

Fix missing Frenchtranslations using new ordered i18 table (on beta)

Fix missing FR translations

---

css/web/style-menu.css
js/web/_main/js/_main.js
js/web/eventquest/css/eventquest.css
js/web/eventquest/js/eventquest.js

Eventquest Button aktiviert sobald Countdown fürs Event bevorsteht

Eventquest Button aktiviert sobald Countdown fürs Event bevorsteht

---

js/web/_i18n/fr.json

Complete missing new FR translations on beta branche

Update FR translation

---

js/web/infoboard/js/infoboard.js

Fixed the infobox message category label (was hardcoded to "Nachricht")

Infobox translation minor issue fix

---

js/web/_i18n/es.json

Update ES-ES translation

---

js/web/_i18n/es.json

Refined some elements in translation

Updating es-ES translation

---

js/web/_i18n/en.json
js/web/_i18n/ru.json
js/web/plunderer/js/plunderer.js

Updated fox plunger and event box russian translation
Aslo added in en "Boxes.Plunderer.FP", you may want update on other language too

Update ru language

---

js/web/plunderer/js/plunderer.js

This is fix for #763
- OtherPlayerService getCityProtections run before PlayerDict is populated, added setTimeout to run in inext event loop tick
- Use PlayerDict as fallback of player info in no record in players db. Basicly players db is needed as cache and for saving player era and last visit time because this info is no availible in player dict. PlayerDict is not best source of info I think, because it will be changed when neighborgoods are changed.
- deffer cleaning of db to 1min, it can be run later after app is up
Screenshot when no info about player in  players db:
Screenshot when no info about player in  players db and PlayersDict:

Fix(plunderer) Add player fallback to PlayerDict and race cond. fixes

---

js/web/plunderer/js/plunderer.js

There is typo in code, so battles are not recorded if defender player id < current player id!

fix(plunderer) Fix typo in comparing with ExtPlayerID

---

js/web/_i18n/es.json

Updated message

---

js/web/_i18n/pl.json

Updated polish translation. Fixed typo @line 336

	modified:   js/web/_i18n/pl.json

---

js/web/stats/css/stats.css

Fix for https://github.com/dsiekiera/foe-helfer-extension/issues/902

Reduce size of stats window is height is <= 1080

---

js/web/stats/js/stats.js

support icons for buildings and other:

Reward icons

---

js/web/stats/js/stats.js

Egypt outpost have own army, need to ignore it

Stats: Dont log army units in stats if visiting outpost (egypt)

---

js/web/_i18n/de.json
js/web/_i18n/en.json
js/web/guildfights/js/guildfights.js
js/web/productions/js/productions.js

Redid the changes i made in master branch in beta now, so it should be easier to merge!

Added efficiency to Production Overview (Beta)

---

js/web/_i18n/de.json
js/web/_i18n/en.json
js/web/productions/js/productions.js

Added area+efficiency to grouped production-table

---

js/web/_i18n/cs.json

Wrong branch. Should be merged to beta branch

Revert "Update cs.json"

---

css/web/style-menu.css
js/web/_i18n/de.json
js/web/_i18n/en.json

Some styling for the update window

---

css/web/style-menu.css
js/web/guildfights/css/guildfights.css

Stat module doesn't look right, my bad. Here's the fix.
Also: HUD change

Fixing buttons, changing bonus HUD

---

css/web/style-menu.css

Wieder ein Problem weniger, sollte keine ungewollten Nebenwirkungen haben - hatte aber noch keine Zeit, diese Änderung ordentlich zu testen 😅 Also gerne nochmals drüberschauen

Fehlerbehebung Counter (Issue #1295 #1349)

---

js/web/_main/js/_main.js

Behebt das in Issue #1375 beschriebene Problem mit der Infobox 👀

Hotfix Infobox (Issue #1375)

---

js/web/_i18n/dk.json

Reverts dsiekiera/foe-helfer-extension#1414
wrong branch

Revert "Update dk.json"

---

js/web/calculator/js/calculator.js

Sollte das von @Nerd2020 in #1471 beschrieben Problem beheben 👍

Fehlerbehebung Kostenrechner (Issue #1471)

---

js/web/ws-chat/js/ws-chat.js

Fehlerbehebung Chat

---

js/web/_main/js/_main.js

Das sollte das Problem beheben (mit @SillyDevil gestestet), die [leeren Nachrichten](https://github.com/dsiekiera/foe-helfer-extension/issues/1439#issuecomment-658705640) tauchen nicht mehr auf

Fehlerbehebung Infobox (Issue #1439)

---

js/background.js
js/inject.js

ToC=Translation of comments
----------------
A lot of people don't speak / understand German (and me the first one) which is problematic when trying to understand the code in order to be able to contribute to it, I offer here the translation of the comments (via G.translate, sorry)...
_Don't hesitate to take a quick look if I haven't made a mistake, I really don't understand a word of German (except transparent words)_

Translation of comments (background.js + inject.js)

---

js/web/eventhandler/js/eventhandler.js

ShowNotifications Einstellung wird nun verwendet

---

js/web/_i18n/de.json
js/web/_i18n/en.json
js/web/market/js/market.js

Added Filter for own trades

---

js/web/guildfights/guildfights.js

Button color change but tooltip not working

 Language Variables fix/Playeroverview resize

---

js/web/_main/js/_main.js
js/web/investment/js/investment.js

Bugfix: 
- Rank was not updated when changed during expansion/level process
Optimizations: 
- moved logic from _main.js to module
- end of expansion of the building is now recognized when visiting the Player GB Overview

Investment Overview: Optimization & Bugfix

---

js/web/_i18n/de.json
js/web/_i18n/en.json
js/web/investment/js/investment.js

add i18n tags + de/en translation

Investment Overview: Translations

---

js/web/battle-assist/js/battle-assist.js

Easy fix to the higher era unit warning appearing all the time. See #2168

Fix higher era unit loss warning error

---

js/web/citymap/css/citymap.css
js/web/citymap/js/citymap.js

according to the suggestion #2294

added color coding to the labels on the town overview

---

js/web/_i18n/en.json
js/web/part-calc/js/part-calc.js

Danger Option now support prefix and/or suffix (Suggestion from Voodora, DE11)
Die "Danger"-Option unterstützt ab sofort Präfix und/oder Suffix für die gefährdeten Plätze (Vorschlag von Voodora, DE11)

Danger Option Improvements

---

js/web/stats/js/stats.js
js/web/unit-gex/js/unit-gex.js
js/web/unit/js/unit.js

und schon das erste kleine Fix😅
P.S. die Verbesserung mit der URL hat mich auch gleich drauf gebracht wie ich auch die spritesheet unnötig machen kann 😄
muss aber noch das mit den abilitie Icons aus frickeln
and already the first small fix 😅
PS the improvement with the URL also gave me the idea of ​​how to make the spritesheet unnecessary 😄
but still have to fiddle with the ability icons

Unit fix 2022.05

---

js/web/fp-collector/js/fp-collector.js

If a visit to a friend's tavern yields a fp, `ReferenceError: Player is not defined` shows up in the console.

Fix ReferenceError: Player is not defined

---

js/web/castle/js/castle.js

Reverts mainIine/foe-helfer-extension#2626

Revert "Update castle display for GEX level 5"

---

js/web/guildfights/js/guildfights.js
js/web/infoboard/js/infoboard.js

Possible fix for the newly added attrition to the table; before the attrition delta overrode the fight delta.
"await GuildFights.UpdateDB" also was missing the attrition values (attrition, diffattr).
+1: Meant to include only guildfights.js in the 1st commit but included another file, hence I reverted the commit and included in the next one correctly just guildfights.js.

guildfights.js: attrition diff fix

---

js/web/calculator/js/calculator.js

Player activity added to calculator

---

js/web/_i18n/en.json

Reverts mainIine/foe-helfer-extension#2710

Revert "Engligh typo correction"

---

changelog-de.md
changelog-en.md

Fixed a gamebreaking bug... Just kidding. Thank you for the shoutout! But please allow me to fix my name 😅

fixed credits

---

js/web/boosts/js/boosts.js

This should fix the infameous crit chance bug

Fixed boosts being influenced by contributed GBs

---

js/web/profile/js/profile.js

also fixed some ASI reliances, and removed unused boost variables

Profile: added goods boost
