js/web/hidden-rewards/js/hidden-rewards.js
3 unused i18n entries where not used in Hidden's reward module.
All words are already in .js and .json translates, just missing in module (marked as 'ToDo' and hardcoded in german).
=> Hidden's reward unused translate

js/web/plunderer/js/plunderer.js
It seems that `is_attacking` is last unit action, not attack of defent flag. Because of using this flag sometimes you can see next wrong att/deff boost calculation:
=> Dont use wrong prop of army "is_attacking"

js/web/read-buildings/js/read-buildings.js
Just add padding and bold font for number to the att/def bonuses
=> Style: Align read-buildings's attack bonuses

js/web/_helper/js/_helper.js
FOE Helper should not send keyboard keys to game if focused inputs in helper windows.
This fix is applied ONLY to all Helper's window
=> Prevent sending keys to game if focused input fields of Boxes

js/inject.js, js/web/_helper/js/_helper.js, js/web/_i18n/en.json, js/web/battle-assist/css/battle-assist.css, js/web/battle-assist/js/battle-assist.js, js/web/campagnemap/js/campagnemap.js, js/web/eventquest/js/eventquest.js, js/web/hidden-rewards/js/hidden-rewards.js, js/web/investment/js/investment.js
Sadly only second (or more) wave can be protected by clicking attack by mistake
=> Add battle assist, protect second wave when only rogues in army

js/web/_helper/js/_helper.js, js/web/settings/js/settings.js
Because we now stop propagation event out from Box some llisteners are not working that use $('body')
In next step we SHOULD replace all `$('body').on(` within `$('#SOME_WINDOW_ID).on`.
Please use window id instead of body as selector of parent element
=> Fix changing language and menu size change

js/web/infoboard/js/infoboard.js
Some times there are errors in infobox, this should fix it
Done use `if (foo=== false)`, but just `if (foo)`.
=> Fix error in info box when testing for falsy

css/web/boxes.css, js/web/_helper/js/_helper.js, js/web/_menu/js/_menu.js, js/web/calculator/js/calculator.js, js/web/citymap/js/citymap.js, js/web/greatbuildings/js/greatbuildings.js, js/web/infoboard/js/infoboard.js, js/web/negotiation/js/negotiation.js, js/web/part-calc/js/part-calc.js, js/web/plunderer/js/plunderer.js, js/web/productions/js/productions.js, js/web/settings/js/settings.js, js/web/technologies/js/technologies.js
1. Multiple subscription to click and other event because of using $('body'). Replaced withing window id. See https://github.com/dsiekiera/foe-helfer-extension/issues/783 https://github.com/dsiekiera/foe-helfer-extension/issues/764
2. Plunderer: Currently if you visited city and open plunderer than you will see not filtered by visited player. Now filter by player even not open plunderer window. This is good because plunderer window is not alwayes opened and currently I need to revisit player to filter by him.
3. When title of window is too long than dont text wrap but show "..."
=> Event fixes and filter plunderer by visited player even if box is not open 

js/web/_i18n/en.json, js/web/stats/js/stats.js
It is too late.. but still good to add support rewards from event
Current know reward types:
```js
La.CONTEXT_DEFAULT = "default";
La.CONTEXT_GUILD_EXPEDITION = "guildExpedition";
La.CONTEXT_CHEST_EVENT = "chestEvent";
La.CONTEXT_ARCHEOLOGY_EVENT = "archeologyEvent";
La.CONTEXT_ARCHEOLOGY_EVENT_AUTO_COLLECT = "archeologyEventAutoCollect";
La.CONTEXT_HALLOWEEN_EVENT = "halloweenEvent";
La.CONTEXT_HALLOWEEN_EVENT_AUTO_COLLECT = "halloweenEventAutoCollect";
La.CONTEXT_CHEST_EVENT_GRAND_PRIZE = "chestEventGrandPrize";
La.CONTEXT_SUMMER_EVENT = "summerEvent";
La.CONTEXT_SUMMER_EVENT_GRAND_PRIZE = "summerEventGrandPrize";
La.CONTEXT_WINTER_EVENT = "winterEvent";
La.CONTEXT_WINTER_EVENT_GRAND_PRIZE = "winterEventGandPrize";
La.CONTEXT_CARNIVAL_EVENT = "carnivalEvent";
La.CONTEXT_SPRING_EVENT = …
```
=> Add event support in stats

js/web/calculator/js/calculator.js
This tweak adds the "max_level" value to the cost calculator to display the open levels of a Great Building, which will make it much easier/faster to find new friends suitable for sniping.
=> Added the "max level" value to the cost calculator

js/web/_main/js/_main.js
Sorry, my last pull request broke the kits feature (removed the Inventory data unintentionally). The change in this pull request reverts that
=> Fixed kits from the last pull

js/web/inventory-tracker/js/inventory-tracker.js, js/web/strategy-points/js/strategy-points.js
- Fixed the issue with adding packs to the inventory when the inventory does not already have packs of that type 
- Fixed the number format of the 'strategy points' text (uses number to locale string now)
- Properly implemented `InvetoryService` (both JSON and raw WS listeners)
- Removed reliance on (buggy) `NoticeIndicatorService` 
- Discontinued keeping track of new packs (there's no need now)
ref: #1059
=> Inventory tracker (strategy points bar) update

js/web/stats/js/stats.js
Diese kleine Änderung dürfte das genannte Problem beheben (lokale Definitionsdifferenzen des Wochenstarts). Bitte prüfen, ob das Problem tatsächlich behoben wurde @frank42hh 👀
=> Fehlerbehebung Statistik (Issue #917)

js/web/notice/css/notice.css
Die `min-width` war beim `noticesBody` größer als beim übergeordneten Element `notices`, was folgenden Fehler verursachte
=> Fehlerbehebung Notizen

js/web/technologies/js/technologies.js
Dieses Leerzeichen hat (unter Anderem) bei den Statistiken zu Bugs geführt, beispielweise funktionierte der "Aktuelles"-Button bei der Zeitalterasuwahl nicht (betrifft Spieler im späten Mittelalter)
=> Fehlerbehebung Statistik

js/web/hidden-rewards/css/hidden-rewards.css
Nur einen kleinen Tippfehler korrigiert 😉 `incidents_crate` → `incident_crates`
=> Fehlerbehebung Ereignisse

js/web/_menu/js/_menu.js, js/web/investment/js/investment.js
Investment Overview didn't close when an event trigger BuildBox()
=> Investment Menu OpenClose Fix

js/web/investment/js/investment.js
Bugfix: If a GB has an reinvestment on the same building with new level which was not done over WebApp then the building stays in list with old values.
=> Bugfix Reinvestment outside the WebApp

js/web/citymap/css/citymap.css
Highlight lower Era function:
- stripes are now thinner than the background color to make them more distinguishable
- the color of the stripes have no longer 50% transparency, so the browser will not render different colors depending on the background
- the angle of the lines in the "Side View" mode were adjusted so they match the "Top View" & the legend as closely as possible, making them easier to recognize
=> citymap optimizations

js/web/citymap/js/citymap.js
in the citymap, the count of buildings of older ages was off by one (for all 4 categories):
i'm not surre if originally the spans of the labels were also counted (as they have the same classes as the rectangles in the map) or if this is still the case, so just to be sure i also changed the selector, so only elements within the #map-container will be counted
=> fix for citymap - old ages count was off by one

js/web/guildfights/js/guildfights.js
The dates under each user's snapshot log on GBG Overview cannot be expanded.
Steps to reproduce:
1. Go to Guild Battleground
2. Open GBG Overview
3. Click on a player entry to open the snapshot log
4. Attempt to expand any date entry.
5. The following error appears:
Uncaught (in promise) Error: Syntax error, unrecognized expression: #gbgdetail_???
at Function.se.error (merged-3rd-party-818a5bbc.js:3:13639)
at se.tokenize (merged-3rd-party-818a5bbc.js:3:21650)
at se.select (merged-3rd-party-818a5bbc.js:3:22477)
at Function.se [as find] (merged-3rd-party-818a5bbc.js:3:7116)
at S.fn.init.find (merged-3rd-party-818a5bbc.js:3:25047)
at new S.fn.init (merged-3rd-party-818a5bbc.js:3:25536)
at S (merged-3rd-party-818a5bbc.js:3:1051)
at Object.BuildDetailViewLog (guildfights.js?v=2.7.0.0:983:29
=> Fix for Guild Battlegrounds snapshot log

js/web/part-calc/js/part-calc.js
_Infobox's_ filter's arrow has class `arrow`, same as _GB Calculator's Copy values'_ settings' arrow.
_GB Calculator's_ arrow binds its click action to all `arrow`s, including _Infobox's_.
Steps to reproduce:
1. Open _Infobox_
1. Open _GB Calculator_
1. Click on _Infobox's_ filter's arrow, _GB Calculator's_ settings window shows up
1. Click on _Infobox's_ filter's arrow again, _GB Calculator's_ settings window hides
1. Close _GB Calculator_
1. Click on _Infobox's_ filter's arrow, `TypeError: Cannot read property 'style' of undefined` shows up in the console.
=> Conflict identifying a html element between Infobox and GB Calculator.

js/web/castle/js/castle.js
Adds the 4 additional GEX encounters
Updates the maximum number of castle points winable from GEX to 900
Corrects typo MaxDailNegotiationsReward to MaxDailyNegotiationsReward
=> Update castle display for GEX level 5

js/web/_i18n/en.json
Minor typo correction in the English translation ("bagde" instead of "badge")
=> Engligh typo correction

js/web/stats/js/stats.js
- fixed date range selection not working correctly, if selecting any date other than today
- fixed date range selection picking a wrong date, if selecting current day and month from a previous year
- fixed date range selection displaying the date range from the previous selection instead of the current selection
=> fixed stats datepicker

changelog-de.md, changelog-en.md, js/web/_i18n/de.json, js/web/_i18n/en.json, js/web/_main/js/_main.js, js/web/citymap/js/citymap.js
added QI stats to BoostsSum
added Coin/Supply boosts to QI building productions replaced QIStats actions with real boost (to include main city boosts)
=> added QI citymap stuff

js/web/part-calc/js/part-calc.js
The cumulative shown in brackets is valid only when no fps are added. This change updates the cumulative to include already added fps by the owner
=> EigenCounter cumulative update
